name: Add comments when a new issue is created
on:
 issues:
   types: [opened]

jobs:
  add_comments:
    name: Add Comments
    if: ${{ toJson(github.event.issue.labels) }}
    runs-on: ubuntu-latest
    steps:
     - run: |
          echo toJson(github.event.issue.labels)
